# Generated by Django 5.1.3 on 2024-11-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_petfood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_foods', to='store.category'),
        ),
    ]
