# Generated by Django 5.1.3 on 2024-11-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_petfood_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet_foods', to='store.category'),
            preserve_default=False,
        ),
    ]
